### ISSUE TITLE
Issue compile source

### ISSUE THREAD

**Issue by Th3AnG3L** [azerothcore/mod-weekend-xp#17] opened 2022-12-29 13:10 UTC
Hello i have download this module and try to install it on latest version on AzerothCore,
Cmake detects the module and no errors shows, then Generate and Open Project with visual studio 2019
But when i try Clean>Build the project it gives error
If i remove the module it builds without issues.

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "void __cdecl AddWeekend_XPScripts(void)" (?AddWeekend_XPScripts@@YAXXZ) referenced in function "void __cdecl AddModulesScripts(void)" (?AddModulesScripts@@YAXXZ)	worldserver	D:\WoW\Build\src\server\apps\modules.lib(ModulesLoader.obj)	1`

**Comment by Th3AnG3L** [comment] 2022-12-29 16:19
found the issue its inside your module.
Correct it like this:
WXP_loader.cpp and change the function name to **AddMod_Weekend_XPScripts**
Then it will allow to be build correct.

**Comment by Helias** [comment] 2022-12-29 21:52
please, if the issue is not fixed in this repository leave it open
Moreover, you could propose the fix of the compilation via Pull Request

**Comment by Th3AnG3L** [comment] 2022-12-29 22:55
Hello, i do not know is coming from module issue or from CMake issue, but if some users may have this issue the same as me, they can follow this steps to solve it. Really do not real cause of Upper Case and LowerCase reading when building.
Please can you include in project to show Icon on character like buff skill that the double EXP weekend started? it would be really good im trying to find a way how to make this.

**Comment by Helias** [comment] 2022-12-29 22:57
I did not work on this module, hope the author can help you.
I am closing the issue, if this issue will be encountered from other users I will re-open it

**Closed by Helias** 2022-12-29 22:57 UTC
